###
POST http://localhost:3000/api/charts/addChart HTTP/1.1
Content-Type: application/json

{
  "chartTitle": "Chart One",
  "chartImg": "https://www.tradingview.com/x/TSxTIOqO/",
  "chartDesc": "this is a chart"
}

###
POST http://localhost:3000/api/charts/comment/5c927a60bc4d9e0fa41ffd34 HTTP/1.1
Content-Type: application/json

{
  "comment": "good chart"
}

###
POST http://localhost:3000/api/charts/reply/5c8b50c57b50263aeab9eb75 HTTP/1.1
Content-Type: application/json

{
  "reply": "ok"
}

###
GET http://localhost:3000/api/charts/posts HTTP/1.1

###
GET http://localhost:3000/api/charts/userPosts HTTP/1.1

###
GET http://localhost:3000/api/charts/singlePost/5c927a60bc4d9e0fa41ffd34 HTTP/1.1